### ISSUE TITLE
NiceGUI iOS Safari Page Reload Bug (+root cause +solution!)

### ISSUE THREAD

**Issue by michaeljandrews** [zauberzeug/nicegui#5802]
### First Check

- [x] I added a very descriptive title here.
- [x] This is not a security issue (those should be reported via the [security advisory](https://github.com/zauberzeug/nicegui/security/advisories/new) instead).
- [x] This is not a Q&A. I am sure something is wrong with NiceGUI or its documentation.
- [x] I used the GitHub search to find a similar [issue](https://github.com/zauberzeug/nicegui/issues) and came up empty.

### Example Code

```python

```

### Description

- Page reloads automatically every few seconds on iOS 26.3 Safari
- No user interaction required to trigger the reload
- Happens before the screen dims (auto-lock set to 5 minutes)
- Occurs with a minimal test case --- a page with a single ui.label with no other components
- Works correctly on all desktop browsers
- Works correctly using NiceGUI v2.9.0 and v2.23.3 on the same mobile device

### NiceGUI Version

3.7.1

### Python Version

3.14.3

### Browser

Safari

### Operating System

iOS

### Additional Context

I found previous issues where this same behavior was reported in the past and dismissed as a bug with Safari or something else Apple-specific. After experiencing this issue myself today, I decided to investigate further.

The test environment was a clean build of NiceGUI on Docker 29.2.1, build a5c7197. The main.py consisted of only a ui.label and nothing else. The site was accessed directly by http (no reverse proxies or other networking complications).

As mentioned above, the page would reload by itself every few seconds. I used the Safari Web Inspector (iPhone connected via USB to Mac) to determine the cause. It showed a JavaScript exception on page load.

> TypeError: crypto.randomUUID is not a function

Also, the WebSocket socket.io connection showed as a spinning/pending state in the Network tab

With some help from AI, I found out the root cause....

Factor 1: NiceGUI v3 introduced an implicit handshake mechanism
NiceGUI v3.7.0 changelog entry: "Perform implicit handshake and fix on_connect called before page is ready." After the WebSocket connects, the client generates a unique tab ID using crypto.randomUUID() and sends a handshake to the server. If the server does not acknowledge within a timeout window, the client executes:

> // nicegui.js --- handshake failure handler
>
> console.log(\'reloading because handshake failed for clientId\');
>
> window.location.reload();

This mechanism did not exist in v2.x, which is why older versions are unaffected.

Factor 2: crypto.randomUUID() is restricted to secure contexts

The Web Cryptography API method crypto.randomUUID() is only available in secure contexts --- pages served over HTTPS or from localhost. This is a web standard enforced by all modern browsers. iOS Safari enforces it strictly.

Since the app was served over plain HTTP (accessed by local IP address), crypto.randomUUID() was not available. Safari threw a TypeError, the tab ID could not be generated, the handshake could not complete, and NiceGUI reloaded the page. This repeated every few seconds indefinitely.

Desktop browsers (Chrome, Firefox) are more permissive about this restriction in some contexts, which is why the bug only appeared on iOS Safari.

**The Fix**

The fix is to serve the application over HTTPS so that crypto.randomUUID() is available as a secure context API. This was implemented using Caddy as a reverse proxy with TLS termination.

**Setup**

-   Caddy added as a Docker service alongside NiceGUI
-   tls internal directive used: Caddy generates its own local CA and signs a certificate
-   nicegui.home hostname configured in local DNS   (this domain name is specific to my local network)
-   Caddy's CA certificate (root.crt) extracted from the container and installed on the iPhone as a trusted root

**Caddyfile configuration**

> nicegui.home {
>
> tls internal
>
> reverse_proxy nicegui:8080
>
> }

**Result**

-   Safari Web Inspector showed no JavaScript errors
-   socket.io connection shown as green and stable in Network tab
-   No further page reloads
-   crypto.randomUUID() executes successfully over HTTPS

--removed unnecessary code sample

Thanks for creating and maintaining NiceGUI, I have been using it since the beginning and find it an invaluable tool. I hope this analysis is useful.

**Comment by evnchn** [comment]
Hello @michaeljandrews 

In NiceGUI code, we always use this helper function:

https://github.com/zauberzeug/nicegui/blob/ab47f68040f87a436f90fe9a720a62228d114295/nicegui/static/nicegui.js#L394-L403

`crypto.randomUUID` may still be used plainly for `ui.mermaid` if source code search is to be trusted:

<img width="657" height="217" alt="Image" src="https://github.com/user-attachments/assets/eb34e01d-9d3e-42b0-9b2b-db28b36ec34a" />

I think you would need to go back to the drawing board with this message back to your AI agent. 

Also, if you have logs **please send it to me**. I believe in Natural Intelligence more than Artificial Intelligence

**Comment by evnchn** [comment]
Also please read https://github.com/zauberzeug/nicegui/issues/5468 which was filed against NiceGUI 3.3.0, thank you.

**Comment by michaeljandrews** [comment]
Hi @evnchn,
  Yes, the section you quoted (line 396) is exactly where the issue is! The function crypto.randomUUID() is not available on http connections and that is where the failure is happening that causes Safari to reload endlessly.

**Comment by evnchn** [comment]
@michaeljandrews But line 396 is inside try-catch. If it fails it should be fine though.

**Comment by michaeljandrews** [comment]
I was able to set a break point in the Safari developer tools and "TypeError: crypto.randomUUID is not a function" was the point where the browser stopped before reloading the page every time. Perhaps the try-catch isn't handling this case properly? When I changed the deployment to use https, the problem went away.

**Comment by evnchn** [comment]
I still believe that a whole lot must have happened between "TypeError: crypto.randomUUID is not a function" and "reloading the page". Possibly the code fell through to the fallback, generated a valid UUID and ran away with it, then hit another error. 

Please note that breakpoint catches do not say everything: If you put a breakpoint on L396 it would trip with an error and fall to `catch` fine still. 

I am really eager to see the raw logs at this point.

**Comment by evnchn** [comment]
Also: If you are using AI to help assess this issue, considering clearing the context window every so often. Perhaps it can re-judge differently the second time.

**Comment by michaeljandrews** [comment]
Thanks for your patience and willingness to look into this stubborn issue! I just reviewed issue #5468 again and now recognize that I did experience unresponsive elements on the page while chasing this issue. That was when I decided to simplify the page to a single ui.label element. I can revert back to http and capture some log data for you. So far, nothing has appeared in the log except the usual "NiceGUI ready to go on http://localhost:8080" , and this is the limit of my human-intelligence! What's the best way to capture more information?  --- Edit forget that last question. The log would be on the browser side?

**Comment by evnchn** [comment]
Yes. Browser logs. I need them since I don't have iOS 26 devices and I'm not inclined to wreck my iPhone 12.

**Comment by michaeljandrews** [comment]
Ok, I reset to http and the page is again reloading by itself on the phone. The break point is capturing the "crypto.randomUUID is undefined" error, but nothing is being logged. According to my AI guy, that means the try-catch is handling it. I did a search of the source and verified only one instance of crypto.randomUUID in the javascript. Running the createRandomUUID function in the console while at the break point generates a valid UUID, so that seems to be working. Any other ideas or suggestions?

**Comment by michaeljandrews** [comment]
Safari is reporting "reloading because connection timed out" (connect_error, nicegui.js:458)
[Error] WebSocket connection to 'ws://[10.1.1.10:5000/_nicegui_ws/socket.io/?client_id=0b2e056b-9937-4d45-a9e7-5c8cb6e8d9c0&next_message_id=0&implicit_handshake=true&document_id=75bd26dc-8802-4e9e-8b13-6c6fcfff4c3e&tab_id=b0aeb9f1-54e3-4fa9-bc50-ae21ef14709c&old_tab_id=25bec8e1-a3b4-4eee-ac1e-c83545cb7452&EIO=4&transport=websocket](http://10.1.1.10:5000/_nicegui_ws/socket.io/?client_id=0b2e056b-9937-4d45-a9e7-5c8cb6e8d9c0&next_message_id=0&implicit_handshake=true&document_id=75bd26dc-8802-4e9e-8b13-6c6fcfff4c3e&tab_id=b0aeb9f1-54e3-4fa9-bc50-ae21ef14709c&old_tab_id=25bec8e1-a3b4-4eee-ac1e-c83545cb7452&EIO=4&transport=websocket)' failed: WebSocket is closed before the connection is established.

(anonymous function) (socket.io.min.js:6:16126)
(anonymous function) (socket.io.min.js:6:8752)
(anonymous function) (socket.io.min.js:6:25606)
n (socket.io.min.js:6:24826)
(anonymous function) (socket.io.min.js:6:25171)
(anonymous function) (socket.io.min.js:6:43419)

**Comment by michaeljandrews** [comment]
According to Mr. AI: "Notice the URL starts with ws://10.1.1.10:5000 — that's an insecure WebSocket. iOS Safari is blocking it for security reasons, just like it blocks crypto.randomUUID over HTTP. The connection never establishes, times out, and NiceGUI reloads."

So the fix of using https is valid, but the root cause was incorrect. There does not appear to be a way to get Safari to connect to an insecure websocket either.

I will suggest that is the final conclusion of this issue. It is likely to be unacceptable to anyone running NiceGUI in a homelab environment using http as they will be unable to reliably access sites with iOS devices.  I have several older NiceGUI applications (<3.0) still running with users that access them using only iPhones. The next steps might be a feature request to preserve the 2.x websocket behaviors as a config option? At minimum, the documentation should be updated to mention that v3.x requires https for iOS Safari and maybe some guidance on a simple https setup. I can't be the only one thinking my code was the reason for the page reloads and getting frustrated by this.

**Comment by evnchn** [comment]
https://bugs.webkit.org/show_bug.cgi?id=302823

https://bugs.webkit.org/show_bug.cgi?id=302561

Seems like still unfixed in iOS 26.3

Using HTTPS or a valid domain instead of IP address may help, but I cannot solidly suggest them since I don't have a device to test...

**Comment by falkoschindler** [comment]
Thanks for the thorough investigation @michaeljandrews, and @evnchn for the back-and-forth debugging and the WebKit bug links.

We looked into the two linked WebKit bugs to pin down the root cause:

- **[Bug 302561](https://bugs.webkit.org/show_bug.cgi?id=302561)** is about iCloud Private Relay breaking multiple WebSocket connections to the same host/port. This was reportedly fixed in iOS 26.3 Beta 2.
- **[Bug 302823](https://bugs.webkit.org/show_bug.cgi?id=302823)** is about WebSocket connections failing when concurrent HTTP requests target the same server in Safari 26. This matches NiceGUI's behavior exactly: the browser fetches the page over HTTP and simultaneously opens a WebSocket to the same host. The bug is marked RESOLVED MOVED to Apple's internal radar (`rdar://165232100`) with no public fix yet.

So the root cause appears to be a **Safari 26 networking regression** (bug 302823), not an intentional security restriction on insecure WebSockets. The HTTPS/Caddy workaround likely helps because it changes the connection dynamics (HTTP/2 multiplexing, different TCP handling) rather than strictly because of the secure context.

That said, there is something we can improve on our side: when the WebSocket connection fails repeatedly, NiceGUI currently enters an **infinite reload loop**. We should consider capping retries and showing an error message instead, so users at least see what's going wrong rather than watching the page flicker endlessly.

For anyone hitting this in the meantime: serving via HTTPS is the most reliable workaround.

**Comment by evnchn** [comment]
> infinite reload loop

Oh no! iOS 26 users may cause false-positive in #5450. We would probably need to tighten our detection logic against a client whose WebSocket is permanently messed up.

**Comment by evnchn** [comment]
_(posted by Claude Code on Evan's behalf)_

Walking back an over-confident dismissal of @evnchn's earlier "iOS 26 may cause false-positive in #5450" point — I had argued the warning couldn't fire on broken-WS clients because the WRONG_SERVER_ID path is gated on a handshake reaching the server. Two things wrong with that:

1. The default transport list in `AppConfig` is `['websocket', 'polling']`, so a client whose WS upgrade fails (bug 302823) **still gets its handshake through via polling fallback** — the mismatch path is reachable even when the WebSocket is permanently broken.
2. The mismatch counter only needs to chain past 3 to fire the warning, and chained mismatches don't require a real session-affinity bug — anything that keeps the served HTML's `server_id` stale relative to the running `core.app._uuid` (a caching CDN ignoring `Cache-Control: no-store`, a `--reload` cascade during active dev edits, a backgrounded iOS tab returning after a server restart) can supply that.

So the original concern stands: this is a diagnostic warning that fires once per process and a single misfire on a pathological client is misleading enough to be worth designing against.

<details>
<summary>Tightening options that don't change the wire protocol</summary>

- raise the threshold from `mismatches > 3` to something less reachable by one stuck client (e.g. `> 10`)
- require mismatches across **≥2 distinct `client_id`s** within a window before warning — a real session-affinity bug surfaces across many clients; one stuck Safari can't trigger alone
- soften the warning text so a misfire isn't actively misleading: *"multi-worker without session affinity, OR a stale page / misbehaving client"*

</details>

@falkoschindler's retry-cap + error-page proposal above is a separate, complementary UX fix for the reload-loop itself.

**Comment by falkoschindler** [comment]
Thanks to Fable 5 we have a possible solution in PR #6103. Feedback welcome!

**Comment by tomsquest** [comment]
I hope the fix will land soon.

I did not comment, but we face the same "handshake failed, reloading" thing.
This is a random thing. Deployment on k8s with Traefik on top, https (I don't know exactly the topology).

**Comment by falkoschindler** [comment]
@tomsquest I hope the PR works for you! We're just merging it. 🤞🏻
